### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by chrisrhayes** [overstory/marklogic-intellij-plugin#1]
- [x] Clone existing repo.
- [x] Check it out.
- [x] Build and run the existing plugin
- [x] Plugin SDK is installed but needs building
- [x] Get full build running via Gradle
- [x] Get plugin build and execute working in IDE sandbox

**Comment by ronhitchens** [comment]
Our repo was forked from [the ligasgr plugin](https://github.com/ligasgr/intellij-xquery) at commit bd1777c, which is broken, at least for the run configuration stuff.  If I checkout the from the latest release (3.2.0) then it works ok.  I'm going to branch off from that point to begin work until  I can fix the problems or until upstream fixes are made.

**Comment by ronhitchens** [comment]
The  [ligasgr plugin](https://github.com/ligasgr/intellij-xquery) has a proper Gradle build setup which runs automated tests.  That's good for CI and release packaging, but it's very tedious to develop a plugin by waiting for a Gradle build and then loading the plugin manually.  IntelliJ has a plugin development mode for quickly testing plugins, but the project must be created as a plugin dev project, which is incompatible with importing the Gradle config (I think, there may be a way).  For now, I'm using a native IntelliJ Plugin Project and leaving the Gradle config for command line usage.  It did require a fair bit of dependency setup, but works OK now.

**Comment by ronhitchens** [comment]
Considering this done.  It's in sufficient shape now to get underway with development.  Some work still needs to be done for CI but there is a separate ticket for that already.  Moving this one on.

**Comment by ligasgr** [comment]
Please have a look on http://ligasgr.github.io/intellij-xquery/collaboration.html
This page has a step where you generate the idea project with modules which allows you to skip manual creation etc. And the created project is a valid Idea Plugin Development project.

**Comment by ronhitchens** [comment]
Thanks Grzegorz.  I had done all everything as per your docs but somehow I wound up setting the Project SDK back to the standard Java 8 SDK.  It's all working smoothly now.  It's been several years since I worked on an IntelliJ plugin, otherwise I would have noticed my mistake.

Thanks again.
