### ISSUE TITLE
Set and Activate Breakpoints in source code

### ISSUE THREAD

**Issue by chrisrhayes** [overstory/marklogic-intellij-plugin#10]
Use the IntelliJ Debugger hooks into the IDE editor to set and activate breakpoints in the source

**Comment by ronhitchens** [comment]
Considering this complete.  Much of the work for this was already in place in Grzegorz's code.  I've added additional code for MarkLogic debugging and all the entry points are being called as expected.  Most of the remaining work will be Issue #9, the interaction with the MarkLogic debugger APIs.

This code is currently on a branch and will be merged when more code is in place.
