### ISSUE TITLE
Contact the owner of the original github repo

### ISSUE THREAD

**Issue by chrisrhayes** [overstory/marklogic-intellij-plugin#14]
Grzegorz Ligas

https://github.com/ligasgr/intellij-xquery
http://grzegorzligas.blogspot.co.uk/

Submit a Pull Request as of commit `4cba7b30de0faf22450ed7187595a459559a1548`, which includes the Quick Documentation enhancements.

**Comment by ronhitchens** [comment]
[Pull Request 213](https://github.com/ligasgr/intellij-xquery/pull/213) sent as of commit `f904311bb9fa47f22f27ebe72e067a0b4832d091` in our repo.

I've also emailed Grzegorz Ligas at ligasgr@gmail.com to tell him what we're doing.
