### ISSUE TITLE
Design debugger UI components to configure connection details for debugging

### ISSUE THREAD

**Issue by chrisrhayes** [overstory/marklogic-intellij-plugin#3]
UI component already exists. Extend it to add fields to specify MarkLogic debugger connection details.

**Comment by ronhitchens** [comment]
This is done and pushed.  Added optional connection details form fields for MarkLogic debugger connection.  Information entered is persisted and retrieved ok.  No code is using the new information yet.

The new fields (currently) only appear on the "MarkLogic (native)" connection type.  It will be added to the "plain" MarkLogic connection type (which uses XQJ) in the future.  For the moment, this form provides enough capability to move on.
