### ISSUE TITLE
c- Invoke individual functions in library modules, with parameter values

### ISSUE THREAD

**Issue by chrisrhayes** [overstory/marklogic-intellij-plugin#5]

**Comment by ronhitchens** [comment]
This may never get implemented.  To call a library function, a main module has to be submitted.  To use the IntelliJ debugger, it must reference a file that it is editing.  A file could be generated automatically and disposed of after running, but the user can create a simple main module just as easily to import a library module and have better control of it.  External variables can be passed in to the main module.

Leaving this in the Icebox, indefinitely.
