### ISSUE TITLE
Version 1.0 is cannot be chosen and it will not install when I download the zip

### ISSUE THREAD

**Issue by peetkes** [overstory/marklogic-intellij-plugin#52]
The latest version V1.0 is not selectable from the intelliJ plugin repository and it also does not install from the zip I downloaded.

**Comment by ronhitchens** [comment]
That's odd.  Jetbrains sent me an email saying it had been approved and was ready to go.  Did you install it from the Plugins section inside IntelliJ?   Note that this version of the plugin requires and IntelliJ build of at least 173.3727.127.  It will refuse to load if your IDE is older than that.  Unfortunately I'm on the road right now and can't look into it for a couple of days.

If you continue to have problems after a day or two, please let me know.

**Comment by dmcassel** [comment]
Data point: IntelliJ just offered me the upgrade to V1, which it applied successfully. I'm using IntelliJ IDEA 2017.3.4 (Ultimate Edition), Build 173.4548.28.

**Comment by peetkes** [comment]
I'm running IntelliJ IDEA 2017.2.6 and I am not able to install V1.0

IntelliJ IDEA 2017.2.6
Build #IC-172.4574.11, built on November 13, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

![intellij xquery plugin](https://user-images.githubusercontent.com/550788/37137918-3be6c860-22a8-11e8-9419-acead4ea4027.png)

**Comment by peetkes** [comment]
And if I try building the zip myself I get:

```
C:\Tools\marklogic-intellij-plugin-ml-v1.0>gradlew build
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reus
ed, use --status for details

> Task :compileJava
C:\Tools\marklogic-intellij-plugin-ml-v1.0\src\main\java\org\intellij\grammar\pa
rser\GeneratedParserUtilBase.java:20: error: package com.intellij.codeInsight.co
mpletion.impl does not exist
import com.intellij.codeInsight.completion.impl.CamelHumpMatcher;
                                               ^
C:\Tools\marklogic-intellij-plugin-ml-v1.0\src\main\java\org\intellij\grammar\pa
rser\GeneratedParserUtilBase.java:21: error: package com.intellij.lang does not
exist
import com.intellij.lang.*;
^
C:\Tools\marklogic-intellij-plugin-ml-v1.0\src\main\java\org\intellij\grammar\pa
rser\GeneratedParserUtilBase.java:22: error: package com.intellij.lang.impl does
 not exist
import com.intellij.lang.impl.PsiBuilderAdapter;

``` 

and a load of similar errors.
Do I miss some dependencies?

**Comment by peetkes** [comment]
Nevermind, I updated the IntelliJ to 2017.3.4 and it picked up the latest version of the plugin

**Comment by peetkes** [comment]
Can close
