### ISSUE TITLE
Support implicitly declared variables within XQuery 3.1 catch clause

### ISSUE THREAD

**Issue by willsthompson** [overstory/marklogic-intellij-plugin#57]
See: https://www.w3.org/TR/xquery-31/#id-try-catch, ex:

    try {
        fn:error(xs:QName('my:error'))
    }
    catch * {
      xdmp:log(($err:code, $err:description, $err:value, $err:module, $err:line-number, $err:column-number, $err:additional))
    }

**Comment by ronhitchens** [comment]
This is done.  Added special case to the resolver for references to these variables when they appear under a catch clause.

**Comment by ronhitchens** [comment]
This is deployed in release 1.1.
