### ISSUE TITLE
a- Eval code from edit buffers (or selections) with optional external variables

### ISSUE THREAD

**Issue by chrisrhayes** [overstory/marklogic-intellij-plugin#6]

**Comment by ronhitchens** [comment]
It will not be easy to evaluate code from highlighted selections in IntelliJ.  It operates on files, and breakpoints need to jump to a specific line in a specific file.  Running code selections will require some advanced stuff to create temporary files, or something.  Considering that to be out of scope for this story.

**Comment by ronhitchens** [comment]
Much of this functionality (to submit an IntelliJ edit buffer/file) is already in place from the work done under the scope of Issue #9.  This story will now be used for finishing out the many remaining issues such as step in/step out/step over, display of variables and values, etc.

Issue #20 will be related to this as well, to enable more convenient running of individual XQuery main module files.

**Comment by ronhitchens** [comment]
This is mostly working reliably now.  Refinements still needed to run/step protocol.  Variables, both global/external and stack-resident, are showing reliably, including type information.

At this point, only "eval" of a standalone main module are supported.  Invoking modules in the appserver root will be implemented in a subsequent story.

A bit more to do before completing this story.

**Comment by ronhitchens** [comment]
- [x] Run out of current Expression
- [x] Step Over
- [x] Step Into
- [x] Step Out
- [x] Set breakpoints while running
- [x] Remove break points while running
- [x] Modify breakpoints while running
- [x] Clear suspended requests on exit - already does this on graceful exit.  no chance to cleanup when debugger Stop button pressed.  Will have to find a way to handle this later.  Any debug-stopped request are cancelled on next run.
- [x] External variables

**Comment by ronhitchens** [comment]
Considering this one done.  Several edge cases still to be handled, but time to move on to dbg:invoke'ing of code in the appserver path.

**Comment by ronhitchens** [comment]
Addressed in version 0.9.0-beta
