### ISSUE TITLE
d- Invoke REST endpoints, with payloads, and capture responses

### ISSUE THREAD

**Issue by chrisrhayes** [overstory/marklogic-intellij-plugin#7]

**Comment by ronhitchens** [comment]
Using this issue for the work related to Capture Appserver run mode.

**Comment by ronhitchens** [comment]
This has been implemented.  Selecting Capture Appserver run mode, then starting the debugger will grab attach to the given appserver (either by name, appserver id or port number).  It will then await the next request to start on that appserver and it will be stopped for debugging.  If no request starts on the appserver with the configurable time limit (two minutes by default), then debugging is canceled.

**Comment by ronhitchens** [comment]
Addressed in version 0.9.0-beta
