### ISSUE TITLE
IDE & ML Debugger API comms module

### ISSUE THREAD

**Issue by chrisrhayes** [overstory/marklogic-intellij-plugin#9]
Develop a module for communicating between the IDE and the MarkLogic Debugger API, keeping it as generic as possible to promote re-use in other contexts.

Abstract ML API endpoints

**Comment by ronhitchens** [comment]
I'm going to consider this one done.  There is still a fair bit of work to do, but the MarkLogic-specific comms class is in place and being used by the code driven by the IDE.  Remaining changes will be refactorings to support the various operations needed by the various run modes, and fleshing out the functionality.
